version: '3'

services:
  db:
    image: postgres
    container_name: stock-track-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock-track-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: